[package]
name = "hone"
version = "0.0.1"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2018"
description = "A shell-friendly parameter search tool inspired by Optuna"
homepage = "https://github.com/sile/hone"
repository = "https://github.com/sile/hone"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
serde = { version="1", features=["derive"] }
serde_json = "1"
structopt = "0.3"
trackable = "0.2"
uuid = { version="0.8", features=["serde", "v4"] }
